'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("./SAPUILandscape.XML")>  _
        Public Property SAPGUIXML() As String
            Get
                Return CType(Me("SAPGUIXML"),String)
            End Get
            Set
                Me("SAPGUIXML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files (x86)\SAP\FrontEnd\SAPgui\saplogon.exe")>  _
        Public Property SAPLogonPath() As String
            Get
                Return CType(Me("SAPLogonPath"),String)
            End Get
            Set
                Me("SAPLogonPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("./ITGCControls.XML")>  _
        Public Property ITGCControl() As String
            Get
                Return CType(Me("ITGCControl"),String)
            End Get
            Set
                Me("ITGCControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00:00:00")>  _
        Public Property Report_FTIME() As String
            Get
                Return CType(Me("Report_FTIME"),String)
            End Get
            Set
                Me("Report_FTIME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("23:59:59")>  _
        Public Property Report_TTIME() As String
            Get
                Return CType(Me("Report_TTIME"),String)
            End Get
            Set
                Me("Report_TTIME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SAPOSS*")>  _
        Public Property ITGC01_OSSID() As String
            Get
                Return CType(Me("ITGC01_OSSID"),String)
            End Get
            Set
                Me("ITGC01_OSSID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("START_REPORT;SA38;TBC1;SE38")>  _
        Public Property ITGC04_TCodeList() As String
            Get
                Return CType(Me("ITGC04_TCodeList"),String)
            End Get
            Set
                Me("ITGC04_TCodeList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC09_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC09_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC09_ApprovedUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC10_ApprovedUserscheck1() As String
            Get
                Return CType(Me("ITGC10_ApprovedUserscheck1"),String)
            End Get
            Set
                Me("ITGC10_ApprovedUserscheck1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC10_ApprovedUserscheck2() As String
            Get
                Return CType(Me("ITGC10_ApprovedUserscheck2"),String)
            End Get
            Set
                Me("ITGC10_ApprovedUserscheck2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC10_ApprovedUserscheck3() As String
            Get
                Return CType(Me("ITGC10_ApprovedUserscheck3"),String)
            End Get
            Set
                Me("ITGC10_ApprovedUserscheck3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC10_ApprovedUserscheck4() As String
            Get
                Return CType(Me("ITGC10_ApprovedUserscheck4"),String)
            End Get
            Set
                Me("ITGC10_ApprovedUserscheck4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC10_ApprovedUserscheck5() As String
            Get
                Return CType(Me("ITGC10_ApprovedUserscheck5"),String)
            End Get
            Set
                Me("ITGC10_ApprovedUserscheck5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC11_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC11_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC11_ApprovedUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC12_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC12_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC12_ApprovedUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC13_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC13_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC13_ApprovedUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC15_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC15_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC15_ApprovedUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SAPMSCUA;RSUSLAND;SAPLSETB;RSM51000_ALV_NEW;SAPMCRFC;RSUSRSUIM;RSUSR002;RSUSR070")>  _
        Public Property ITGC16_ProgramName() As String
            Get
                Return CType(Me("ITGC16_ProgramName"),String)
            End Get
            Set
                Me("ITGC16_ProgramName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;IT_FF_SEC")>  _
        Public Property ITGC17_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC17_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC17_ApprovedUsers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\Downloads")>  _
        Public Property DownloadDestination() As String
            Get
                Return CType(Me("DownloadDestination"),String)
            End Get
            Set
                Me("DownloadDestination") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ITGCBOT;FF*;SAPOSS*")>  _
        Public Property ITGC08_ApprovedUsers() As String
            Get
                Return CType(Me("ITGC08_ApprovedUsers"),String)
            End Get
            Set
                Me("ITGC08_ApprovedUsers") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AuditX.My.MySettings
            Get
                Return Global.AuditX.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
